# Generated by Django 3.2.4 on 2021-06-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_remove_worker_to_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToBookingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_book', models.DateTimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.worker')),
            ],
        ),
    ]
