# Generated by Django 3.2.4 on 2021-06-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_worker_to_book'),
        ('to_book_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToBookingClient',
            new_name='ToBookClient',
        ),
    ]
