# Generated by Django 3.2.4 on 2021-06-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_worker_to_book'),
        ('to_book_client', '0002_rename_tobookingclient_tobookclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobookclient',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.client'),
            preserve_default=False,
        ),
    ]
