# Generated by Django 3.2.4 on 2021-06-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210606_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='to_book',
        ),
    ]
